# Generated by Django 3.2.13 on 2023-09-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menções_honrosas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=50)),
                ('nome_completo', models.CharField(max_length=70)),
                ('assistencias', models.CharField(max_length=20)),
                ('posicao', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Top_5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols', models.CharField(max_length=50)),
                ('partidas', models.CharField(max_length=70)),
                ('titulos', models.CharField(max_length=20)),
                ('nascimento', models.DateField()),
            ],
        ),
    ]
