# Generated by Django 3.2.13 on 2023-09-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDoRodrigo', '0002_rename_nascimento_top_5_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menções_honrosas',
            old_name='atividade',
            new_name='gols',
        ),
        migrations.RenameField(
            model_name='menções_honrosas',
            old_name='nome_completo',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='menções_honrosas',
            old_name='posicao',
            new_name='partidas',
        ),
        migrations.RenameField(
            model_name='menções_honrosas',
            old_name='assistencias',
            new_name='titulos',
        ),
        migrations.AlterField(
            model_name='top_5',
            name='nome',
            field=models.CharField(max_length=70),
        ),
    ]
