# Generated by Django 3.2.13 on 2023-09-23 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appDoRodrigo', '0003_auto_20230923_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='top_5',
            old_name='nome',
            new_name='nome_do_jogador',
        ),
    ]
