# Generated by Django 3.2.13 on 2023-09-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDoRodrigo', '0005_rename_nome_do_jogador_top_5_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('gols', models.CharField(max_length=50)),
                ('partidas', models.CharField(max_length=70)),
                ('titulos', models.CharField(max_length=20)),
            ],
        ),
    ]
